name: calendar_views
version: 0.5.2

description: Collection of customisable calendar related widgets for Flutter.

author: ZedTheLed<zedtheled@gmail.com>

homepage: https://github.com/ZedTheLed/calendar_views

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.2.4
  quiver: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: '>=2.0.0 <3.0.0'
